version: '3'
services:
  tf-jupiter:
    container_name: tf-jupiter
    build: 
      context: .
      dockerfile: Docker/jupyter/.DockerFile
    ports:
      - 8888:8888
    volumes:
      - .:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tensorboard:
    container_name: tensorboard
    build: 
      context: .
      dockerfile: Docker/tensorboard/.DockerFile
    ports:
      - 6006:6006
    volumes:
      - ./logs:/logs